CREATE VIEW [dbo].[VW_TTGRP]
AS
WITH C AS 
( 
SELECT SNO,EMPID,DATE,TIME,INOUT,LAG_TIME,LAG_SS,MAX_OUTSIDE,relevantid
,max(relevantid) OVER (ORDER BY EMPID,DATE,TIME ROWS UNBOUNDED PRECEDING) AS GRP
FROM (
SELECT 
ROW_NUMBER() OVER (ORDER BY A.EMPID,A.DATE,A.TIME,A.Lag_SS desc) as sno,
A.EMPID,A.DATE,A.TIME,A.INOUT,A.LAG_TIME,A.LAG_SS,B.Max_Outside
FROM VW_TTLAG A WITH (NOLOCK)
LEFT JOIN VW_TT_MNWT B WITH (NOLOCK)
ON A.DATE = B.DATE
AND A.EMPID = B.EMPID
AND A.LAG_SS = B.Max_outside
) X
CROSS APPLY (VALUES (CASE WHEN MAX_OUTSIDE is not null then sno END )) AS a(relevantid)
)
SELECT *,
MIN(DATE) OVER (PARTITION BY GRP ORDER BY SNO ROWS UNBOUNDED PRECEDING ) AS maxcol1ingrp
 FROM C
