CREATE VIEW [dbo].[VW_TT]
AS
SELECT EMPID,DATE,MAX(GRP) AS GRP,MAX(IN_TIME) AS IN_TIME,MAX(OUT_TIME) AS OUT_TIME FROM 
(
SELECT EMPID,GRP,maxcol1ingrp,MIN(DATE) AS DATE
,MIN(CONVERT(DATETIME,DATE)+CONVERT(DATETIME,TIME)) AS IN_TIME
,MAX(CONVERT(DATETIME,DATE)+CONVERT(DATETIME,TIME)) AS OUT_TIME
 FROM VW_TTGRP
GROUP BY EMPID,GRP,maxcol1ingrp
) X
GROUP BY EMPID,DATE


